name: Terraform Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/env/dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/env/dev

    - name: Terraform Import OpenAI
      run: |
        terraform import azurerm_cognitive_account.openai "/subscriptions/9eeff072-d8d5-4fba-b08e-fa6657f93afe/resourceGroups/rg-ai-rag/providers/Microsoft.CognitiveServices/accounts/openai-rag-northcentralus"
      working-directory: terraform/env/dev

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform/env/dev

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
  apply:
    needs: plan
    runs-on: ubuntu-latest

    environment:
      name: dev  

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/env/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/env/dev
